name: Publish Package
on: [push]

jobs:
  build:
    name: pypi
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build package
        run: |
          python3 -m pip install --user --upgrade setuptools twine wheel
          python3 setup.py sdist
      - name: pypirc
        env:
          PYPI_USERNAME: ${{ secrets.pypi_username }}
          PYPI_PASSWORD: ${{ secrets.pypi_password }}
        run: |
         printf "[distutils]\nindex-servers =\n\tpypi\n\n[pypi]\nrepository: https://upload.pypi.org/legacy/\nusername: ${PYPI_USERNAME}\npassword: ${PYPI_PASSWORD}">~/.pypirc
         python3 -m twine upload dist/*

