name: Publish Package
on: [push]

jobs:
  build:
    name: pypi
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build package
        run: |
          python3 -m pip install --upgrade setuptools twine wheel
          python3 setup.py sdist
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.pypi_username }}
          password: ${{ secrets.pypi_password }}
